config/routes.rb
Rails.application.routes.draw do
  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/auth/login" => "auth0#login"
  get "/auth/logout" => "auth0#logout"

  get 'results/show'

  root 'dashboard#index'
  get 'dashboard/index'
  post 'votefor/:choice', to: 'votes#receive_vote'
  post 'vote/sms', to: 'votes#receive_sms'

  resources :participants
  resources :restricted_numbers

  resources :votings do
    member do
      post 'start'
      post 'stop'
      post 'copy_registrations'
    end
    get :results
    resources :registrations
    resources :votes, only: [:index]
  end


end

app/models/voting.rb
class Voting < ApplicationRecord
  scope :draft, -> { where(status: 'draft') }

  has_many :registrations, :dependent => :restrict_with_error
  has_many :participants, through: :registrations
  has_many :votes, through: :registrations

  validates :name, presence: true


  def self.current
    Voting.last
  end

  def current?
    Voting.current == self
  end


  def start!
    return false unless startable?
    self.running = true
    save
  end

  def stop!
    return false unless stoppable?
    self.running = false
    save
  end

  def startable?
    not self.running and self.current?
  end

  def stoppable?
    self.running
  end

end

app/controllers/votings_controller.rb
class VotingsController < SecuredController
  before_action :set_voting, only: [:show, :edit, :update, :destroy, :start, :stop, :copy_registrations]
  skip_before_action :login_filter, :only => [:index, :show, :results] unless Rails.env.test?

  # GET /votings
  # GET /votings.json
  def index
    @votings = Voting.all.order(:id)
  end

  # GET /votings/1
  # GET /votings/1.json
  def show
  end

  # GET /votings/new
  def new
    @voting = Voting.new
  end

  # GET /votings/1/edit
  def edit
  end

  # POST /votings
  # POST /votings.json
  def create
    @voting = Voting.new(voting_params)

    respond_to do |format|
      if @voting.save
        flash[:success] = 'Voting was successfully created.'
        format.html { redirect_to votings_path }
        format.json { render :show, status: :created, location: @voting }
      else
        format.html { render :new }
        format.json { render json: @voting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votings/1
  # PATCH/PUT /votings/1.json
  def update
    respond_to do |format|
      if @voting.update(voting_params)
        flash[:success] = 'Voting was successfully updated.'
        format.html { redirect_to votings_path }
        format.json { render :show, status: :ok, location: @voting }
      else
        format.html { render :edit }
        format.json { render json: @voting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votings/1
  # DELETE /votings/1.json
  def destroy
    if @voting.destroy
      respond_to do |format|
        format.html {
          flash[:success] = 'Voting was successfully deleted.'
          redirect_back fallback_location: votings_url
        }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html {
          flash[:danger] = 'Could not delete voting.'
          redirect_back fallback_location: votings_url
        }
        format.json { head :no_content }
      end
    end

  end

  # POST /votings/1/start
  def start
    if @voting.start!
      flash[:success] = "Voting started"
    else
      flash[:danger] = "Failed to start voting!"
    end
    redirect_back(fallback_location: @voting)
  end

  # POST /votings/1/stop
  def stop
    if @voting.stop!
      flash[:success] = "Voting stopped"
    else
      flash[:danger] = "Failed to stop voting!"
    end
    redirect_back(fallback_location: @voting)
  end

  def results
    @voting = Voting.find(params[:voting_id])
    active_votes =  @voting.votes.active.group(:registration_id).count
    @voting.registrations.each do |r|
      r.votecount = active_votes[r.id].to_i
    end
    @voting

  end

  def copy_registrations
    if @voting.id == params[:voting][:id].to_i
      flash[:danger] = "Cannot copy from itself"
    elsif @voting.registrations.count > 0
      flash[:danger] = "Failed to copy. There are registrations already present."
    else
      Voting
          .find(params[:voting][:id])
          .registrations
          .map(&:dup)
          .map{|r| r.voting=@voting; r}
          .map(&:save!)
    end
    redirect_back(fallback_location: @voting)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voting
      @voting = Voting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voting_params
      params.require(:voting).permit(:name)
    end
end

app/helpers/votings_helper.rb
module VotingsHelper
end

app/views/votings/_form.html.slim
= form_for @voting do |f|
  - if @voting.errors.any?
    #error_explanation
      h2 = "#{pluralize(@voting.errors.count, "error")} prohibited this voting from being saved:"
      ul
        - @voting.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name, "Nimi"
    = f.text_field :name
  .actions = f.submit "Muuda"

app/views/votings/edit.html.slim
h1 Editing voting

== render 'form'

= link_to 'Tagasi', votings_path

app/views/votings/index.html.slim
h1 Hääletused

table.table
  thead
    tr
      th
      th Nimi
      th Staatus
      th
      th
      th
      th
      th
      th
      th

  tbody
    - @votings.each do |voting|
      tr
        td
          b = 'Praegune' if voting.current?
        td = voting.name
        td = voting.running? ? "* Käib *" : "Peatatud"
        td = link_to 'Registreeringud', voting_registrations_path(voting)
        td = link_to 'Hääled', voting_votes_path(voting)
        td
          b = link_to 'Tulemused', voting_results_path(voting)
        td
          = (link_to 'Alusta', [:start, voting], data: {confirm: "Alustan hääletust '#{voting.name}'?"}, method: :post) if voting.startable?
          = (link_to 'Peata', [:stop, voting], data: {confirm: "Peatan hääletuse '#{voting.name}'?"}, method: :post) if voting.stoppable?
        td = link_to 'Muuda', edit_voting_path(voting)
        td = link_to 'Kustuta', voting, data: {confirm: "Delete #{voting.name}?"}, method: :delete

br

= link_to 'Tagasi', '/'
== " | "
= link_to_if @votings.none?(&:running?), 'Lisa hääletus', new_voting_path
= " - Uue hääletuse lisamiseks peata käimasolev hääletus!" if @votings.any?(&:running?)

app/views/votings/new.html.slim
h3 New voting

= form_for @voting do |f|
  - if @voting.errors.any?
    #error_explanation
      h2 = "#{pluralize(@voting.errors.count, "error")} prohibited this voting from being saved:"
      ul
        - @voting.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name, "Nimi"
    = f.text_field :name
  .actions = f.submit "Lisa"

= link_to 'Tagasi', votings_path

app/views/votings/results.html.slim
h3 = @voting.name
h3 Registreeringud

table.table
  thead
    tr
      th Riik
      th Artist
      th Pealkiri
      th Hääli
      th Koht


  tbody
    - @voting.registrations.sort_by(&:votecount).reverse.each_with_index do |registration, i|
      tr
        td = registration.participant.country
        td = registration.participant.artist
        td = registration.participant.title
        td = registration.votecount
        td = i+1
    tr
      td colspan=3 align="right"
        b Kokku:
      td colspan=2
        b
          = @voting.registrations.map(&:votecount).map(&:to_i).sum

= link_to 'Tagasi', votings_path