config/routes.rb
Rails.application.routes.draw do
  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/auth/login" => "auth0#login"
  get "/auth/logout" => "auth0#logout"

  get 'results/show'

  root 'dashboard#index'
  get 'dashboard/index'
  post 'votefor/:choice', to: 'votes#receive_vote'
  post 'vote/sms', to: 'votes#receive_sms'

  resources :participants
  resources :restricted_numbers

  resources :votings do
    member do
      post 'start'
      post 'stop'
      post 'copy_registrations'
    end
    get :results
    resources :registrations
    resources :votes, only: [:index]
  end


end

app/models/participant.rb
class Participant < ApplicationRecord
  has_many :registrations, :dependent => :restrict_with_error
  has_many :votings, through: :registrations
  has_many :votes, through: :registrations

  validates :country, presence: true
  validates :artist, presence: true
  validates :title, presence: true

  def to_string
    country + " | " + artist + " | " + title
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < SecuredController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]
  skip_before_action :login_filter, :only => [:index, :show] unless Rails.env.test?

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        flash[:success] = 'Participant was successfully created.'
        format.html { redirect_to participants_path }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to participants_path, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    respond_to do |format|
      if @participant.destroy
        flash[:success] = 'Participant was successfully destroyed.'
        format.html { redirect_to participants_path }
        format.json { head :no_content }
      else
        flash[:danger] = 'Participant was NOT destroyed.'
        format.html { redirect_to participants_path }
        format.json { render json: @participant.errors, status: :internal_server_error }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:country, :artist, :title)
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.slim
= form_for @participant do |f|
  - if @participant.errors.any?
    #error_explanation
      h2 = "#{pluralize(@participant.errors.count, "error")} prohibited this participant from being saved:"
      ul
        - @participant.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :country, "Riik"
    = f.text_field :country
  .field
    = f.label :artist
    = f.text_field :artist
  .field
    = f.label :title, "Lugu"
    = f.text_field :title
  .actions = f.submit

app/views/participants/edit.html.slim
h3 Esineja muutmine

== render 'form'

= link_to 'Tagasi', participants_path

app/views/participants/index.html.slim
h3 Esinejate nimekiri

table.table
  thead
    tr
      th Riik
      th Artist
      th Lugu
      th
      th

  tbody
    - @participants.each do |participant|
      tr
        td = participant.country
        td = participant.artist
        td = participant.title
        td = link_to 'Muuda', edit_participant_path(participant)
        td = link_to 'Kustuta', participant, data: {confirm: 'Oled sa kindel?'}, method: :delete

= link_to 'Tagasi', '/'
== " | "
= link_to 'Lisa esineja', new_participant_path

app/views/participants/new.html.slim
h3 Uus esineja

== render 'form'

= link_to 'Tagasi', participants_path