config/routes.rb
Rails.application.routes.draw do
  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/auth/login" => "auth0#login"
  get "/auth/logout" => "auth0#logout"

  get 'results/show'

  root 'dashboard#index'
  get 'dashboard/index'
  post 'votefor/:choice', to: 'votes#receive_vote'
  post 'vote/sms', to: 'votes#receive_sms'

  resources :participants
  resources :restricted_numbers

  resources :votings do
    member do
      post 'start'
      post 'stop'
      post 'copy_registrations'
    end
    get :results
    resources :registrations
    resources :votes, only: [:index]
  end


end

app/models/restricted_number.rb
class RestrictedNumber < ApplicationRecord
  validates :number, presence: true
end

app/controllers/restricted_numbers_controller.rb
class RestrictedNumbersController < SecuredController
  before_action :set_restricted_number, only: [:show, :edit, :update, :destroy]
  skip_before_action :login_filter, :only => [:index, :show] unless Rails.env.test?

  # GET /restricted_numbers
  # GET /restricted_numbers.json
  def index
    @restricted_numbers = RestrictedNumber.all
  end

  # GET /restricted_numbers/1
  # GET /restricted_numbers/1.json
  def show
  end

  # GET /restricted_numbers/new
  def new
    @restricted_number = RestrictedNumber.new
  end

  # GET /restricted_numbers/1/edit
  def edit
  end

  # POST /restricted_numbers
  # POST /restricted_numbers.json
  def create
    @restricted_number = RestrictedNumber.new(restricted_number_params)

    respond_to do |format|
      if @restricted_number.save
        flash[:success] = 'Piiratud number lisatud'
        format.html { redirect_to restricted_numbers_path }
        format.json { render :show, status: :created, location: @restricted_number }
      else
        format.html { render :new }
        format.json { render json: @restricted_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restricted_numbers/1
  # PATCH/PUT /restricted_numbers/1.json
  def update
    respond_to do |format|
      if @restricted_number.update(restricted_number_params)
        flash[:success] = 'Piiratud number uuendatud'
        format.html { redirect_to restricted_numbers_path}
        format.json { render :show, status: :ok, location: @restricted_number }
      else
        format.html { render :edit }
        format.json { render json: @restricted_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restricted_numbers/1
  # DELETE /restricted_numbers/1.json
  def destroy
    @restricted_number.destroy
    respond_to do |format|
      flash[:success] = 'Piiratud number eemaldatud!'
      format.html { redirect_to restricted_numbers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restricted_number
      @restricted_number = RestrictedNumber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restricted_number_params
      params.require(:restricted_number).permit(:name, :number)
    end
end

app/helpers/restricted_numbers_helper.rb
module RestrictedNumbersHelper
end

app/views/restricted_numbers/_form.html.slim
= form_for @restricted_number do |f|
  - if @restricted_number.errors.any?
    #error_explanation
      h2 = "#{pluralize(@restricted_number.errors.count, "error")} prohibited this restricted_number from being saved:"
      ul
        - @restricted_number.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name, "Nimi"
    = f.text_field :name
  .field
    = f.label :number, "Telefoninumber"
    = f.text_field :number
  .actions = f.submit

app/views/restricted_numbers/edit.html.slim
h3 Piiratud numbri muutmine

== render 'form'

= link_to 'Tagasi', restricted_numbers_path

app/views/restricted_numbers/index.html.slim
h1 Listing restricted_numbers

table
  thead
    tr
      th Name
      th Number
      th
      th

  tbody
    - @restricted_numbers.each do |restricted_number|
      tr
        td = restricted_number.name
        td = restricted_number.number
        td = link_to 'Muuda', edit_restricted_number_path(restricted_number)
        td = link_to 'Kustuta', restricted_number, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'Uus piiratud number', new_restricted_number_path

app/views/restricted_numbers/new.html.slim
h3 Uus piiratud number

== render 'form'

= link_to 'Back', restricted_numbers_path