config/routes.rb
Rails.application.routes.draw do
  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/auth/login" => "auth0#login"
  get "/auth/logout" => "auth0#logout"

  get 'results/show'

  root 'dashboard#index'
  get 'dashboard/index'
  post 'votefor/:choice', to: 'votes#receive_vote'
  post 'vote/sms', to: 'votes#receive_sms'

  resources :participants
  resources :restricted_numbers

  resources :votings do
    member do
      post 'start'
      post 'stop'
      post 'copy_registrations'
    end
    get :results
    resources :registrations
    resources :votes, only: [:index]
  end


end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title EuroVintVoting
    = csrf_meta_tags
    = javascript_include_tag :application
    = stylesheet_link_tag 'application', media: 'all'

    = stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css"
    = stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
  body
    nav class="navbar navbar-fixed-top navbar-light bg-faded"
      a class="navbar-brand" href="/" Sahtlist saali
      ul class="nav navbar-nav"
        li.nav-item
          a.nav-link href="#{participants_path}" Esinejad
        li.nav-item
          a.nav-link href="#{votings_path}"Hääletused
        li.nav-item
          a.nav-link href="#{restricted_numbers_path}" Piiratud numbrid
      -unless @user_session.nil?
        ul class="nav navbar-nav float-xs-right"
          li.nav-item
            span.navbar-text class="text-muted" = "Tere " + @user_session['info']['name']
          li.nav-item
            span class="glyphicon glyphicon-log-out"
            a.nav-link href="/auth/logout" Logi välja

    div.container
      - flash.each do |key, value|
        div class="alert alert-#{key}" = value
      /this line keeps yield in place
      == yield

  = javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js"